apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: aks-devops
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
